### PR TITLE
fix redis-sentinel selector role value

### PR DESCRIPTION
**Pull request by whzghb**
fix redis-sentinel selector role value

### CODE REVIEW

**Review by shubham-cmyk — CHANGES_REQUESTED** [review]
can you bump the version in the Chart.yaml

**Comment by whzghb** [comment]
> can you bump the version in the Chart.yaml



> can you bump the version in the Chart.yaml

to 0.15.10?

**Comment by shubham-cmyk** [comment]
> > can you bump the version in the Chart.yaml
> 
> > can you bump the version in the Chart.yaml
> 
> to 0.15.10?

yes but  only for the sentinel

**Comment by shubham-cmyk** [comment]
```
To add your Signed-off-by line to every commit in this branch:

Ensure you have a local copy of your branch by [checking out the pull request locally via command line](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally).
In your local branch, run: git rebase HEAD~1 --signoff
Force push your changes to overwrite the branch: git push --force-with-lease origin fix-redis-sentinel-selector-role-value
```

https://github.com/OT-CONTAINER-KIT/helm-charts/pull/164/checks?check_run_id=17724569386

**Comment by whzghb** [comment]
> yes but only for the sentinel>
> 
> Also it would be good if you sign off your commit.

ok，i have resubmitted it

**Pull request merged**
