### PR TITLE
Fix redis-cluster redis_setup_type

### PR DESCRIPTION
**Pull request by oleg-glushak**

### CODE REVIEW

**Comment by oleg-glushak** [comment]
cc. @iamabhishek-dubey

**Comment by iamabhishek-dubey** [comment]
Looks good, can you please sign off your commit https://github.com/OT-CONTAINER-KIT/helm-charts/pull/11/checks?check_run_id=3819953289

**Comment by iamabhishek-dubey** [comment]
@oleg-glushak please fix the merge conflicts

**Review by iamabhishek-dubey — CHANGES_REQUESTED** [review]
Please update the minor version of the chart

**Comment by allisthere2love** [comment]
Hi, how's this fix?
We've started to use the operator, but bumped into this issue. Did a little workaround, but as there's is already a PR to fix it, better to solve this one.

**Comment by SiM22** [comment]
This is really needed, can the maintainers push this change asap as it seems the original poster is not actively looking at this PR @iamabhishek-dubey

**Pull request closed without merging**
